# Generated by Django 4.0 on 2022-01-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='time1',
            field=models.TimeField(auto_now=True),
        ),
    ]
